"""Run the tournament twice, verify outputs, and record deterministic hashes."""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
GENERATED = (
    "input_manifest.json", "nd_scorecard.csv", "nd_group_oof.csv", "nd_external_raw.csv",
    "nd_extrapolation.csv", "nd_parameters.csv", "quality_scorecard.csv",
    "quality_leave_N_oof.csv", "quality_transfer.csv", "quality_cluster_bootstrap.csv",
    "quality_parameter_intervals.csv", "source_conditional_holdout.csv",
    "source_leave_B5_out.csv", "B6_B8_exact_overlap.csv", "quality_direction_by_source.csv",
    "mechanism_diagnostic.json", "lambda_p_scenarios.csv", "problem2_model_tournament.csv",
    "selection.json", "verification_results.json",
)


def hashes():
    return {name: hashlib.sha256((HERE / name).read_bytes()).hexdigest() for name in GENERATED}


def run():
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
    subprocess.run([sys.executable, str(HERE / "run_tournament.py")], check=True, env=env)
    subprocess.run([sys.executable, str(HERE / "verify_tournament.py")], check=True, env=env)


def main():
    run()
    first = hashes()
    run()
    second = hashes()
    result = {"deterministic": first == second, "verified_files": second,
              "python": sys.version, "PYTHONDONTWRITEBYTECODE": "1"}
    (HERE / "reproduction.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Deterministic outputs: {result['deterministic']} ({len(second)} files)")
    if not result["deterministic"]:
        raise AssertionError("Repeated runs changed generated bytes")


if __name__ == "__main__":
    main()
